// ── Mock data for OMANYE frontend shell ───────────────────────────────────────

export const STATS = {
  totalBeneficiaries: 14_832,
  activeProjects: 12,
  fieldWorkers: 47,
  reportsThisMonth: 28,
  donorsActive: 63,
  grantsFunded: 9,
  budgetUtilized: 68,
  impactScore: 82,
}

export const PROJECTS = [
  {
    id: 'p1',
    name: 'Clean Water Initiative – Volta Region',
    status: 'active',
    region: 'Volta Region, GH',
    lead: 'Kwame Asante',
    team: ['Kwame Asante', 'Abena Mensah', 'Femi Ojo', 'Chioma Adeke'],
    beneficiaries: 3_200,
    target: 5_000,
    budget: 120_000,
    spent: 74_500,
    progress: 64,
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    tags: ['WASH', 'Infrastructure'],
  },
  {
    id: 'p2',
    name: 'Girls\' Education Access Program',
    status: 'active',
    region: 'Northern Region, GH',
    lead: 'Amara Osei',
    team: ['Amara Osei', 'Seun Adeyemi', 'Grace Boateng'],
    beneficiaries: 1_840,
    target: 2_500,
    budget: 85_000,
    spent: 52_300,
    progress: 73,
    startDate: '2024-01-15',
    endDate: '2024-11-30',
    tags: ['Education', 'Gender'],
  },
  {
    id: 'p3',
    name: 'Community Health Workers Training',
    status: 'active',
    region: 'Ashanti Region, GH',
    lead: 'Dr. Kofi Ntim',
    team: ['Dr. Kofi Ntim', 'Naomi Asare', 'Emmanuel Darko'],
    beneficiaries: 480,
    target: 600,
    budget: 42_000,
    spent: 38_900,
    progress: 80,
    startDate: '2024-03-01',
    endDate: '2024-09-30',
    tags: ['Health', 'Capacity Building'],
  },
  {
    id: 'p4',
    name: 'Smallholder Farmer Cooperative',
    status: 'pending',
    region: 'Brong-Ahafo, GH',
    lead: 'Yaw Darko',
    team: ['Yaw Darko', 'Abena Mensah'],
    beneficiaries: 0,
    target: 2_000,
    budget: 95_000,
    spent: 5_200,
    progress: 5,
    startDate: '2024-07-01',
    endDate: '2025-06-30',
    tags: ['Agriculture', 'Livelihoods'],
  },
  {
    id: 'p5',
    name: 'Urban Refugee Legal Aid Clinic',
    status: 'active',
    region: 'Greater Accra, GH',
    lead: 'Adwoa Poku',
    team: ['Adwoa Poku', 'Kojo Mensah', 'Zainab Ibrahim', 'Tunde Okafor'],
    beneficiaries: 920,
    target: 1_200,
    budget: 60_000,
    spent: 41_200,
    progress: 76,
    startDate: '2024-02-15',
    endDate: '2024-12-31',
    tags: ['Protection', 'Legal'],
  },
  {
    id: 'p6',
    name: 'Maternal Health Outreach – Tamale',
    status: 'completed',
    region: 'Northern Region, GH',
    lead: 'Dr. Ama Owusu',
    team: ['Dr. Ama Owusu', 'Akosua Frimpong'],
    beneficiaries: 1_850,
    target: 1_800,
    budget: 55_000,
    spent: 54_200,
    progress: 100,
    startDate: '2023-10-01',
    endDate: '2024-04-30',
    tags: ['Health', 'Maternal'],
  },
]

export const BENEFICIARIES = [
  { id: 'b1',  name: 'Ama Asantewaa',   age: 34, gender: 'F', region: 'Volta',      project: 'Clean Water Initiative',      status: 'enrolled',  date: '2024-03-10' },
  { id: 'b2',  name: 'Kweku Mensah',    age: 28, gender: 'M', region: 'Northern',   project: 'Girls\' Education Access',    status: 'active',    date: '2024-02-20' },
  { id: 'b3',  name: 'Fatima Al-Amin',  age: 19, gender: 'F', region: 'Northern',   project: 'Girls\' Education Access',    status: 'active',    date: '2024-02-22' },
  { id: 'b4',  name: 'Kofi Boateng',    age: 45, gender: 'M', region: 'Ashanti',    project: 'Community Health Workers',    status: 'completed', date: '2024-03-05' },
  { id: 'b5',  name: 'Abena Frimpong',  age: 31, gender: 'F', region: 'Accra',      project: 'Urban Refugee Legal Aid',     status: 'active',    date: '2024-03-18' },
  { id: 'b6',  name: 'Ibrahim Seidu',   age: 52, gender: 'M', region: 'Brong-Ahafo','project': 'Smallholder Farmer',        status: 'enrolled',  date: '2024-06-01' },
  { id: 'b7',  name: 'Adjoa Koomson',   age: 24, gender: 'F', region: 'Volta',      project: 'Clean Water Initiative',      status: 'active',    date: '2024-03-12' },
  { id: 'b8',  name: 'Yaw Opoku',       age: 39, gender: 'M', region: 'Ashanti',    project: 'Community Health Workers',    status: 'active',    date: '2024-03-06' },
  { id: 'b9',  name: 'Naomi Acheampong',age: 27, gender: 'F', region: 'Accra',      project: 'Urban Refugee Legal Aid',     status: 'active',    date: '2024-03-20' },
  { id: 'b10', name: 'Emmanuel Tetteh', age: 41, gender: 'M', region: 'Volta',      project: 'Clean Water Initiative',      status: 'enrolled',  date: '2024-03-14' },
]

export const DONORS = [
  { id: 'd1', name: 'Rockefeller Foundation',  type: 'Foundation', country: 'US',  amount: 250_000, given: 180_000, status: 'active',   lastGift: '2024-03-01', projects: ['p1','p2'] },
  { id: 'd2', name: 'USAID',                   type: 'Government', country: 'US',  amount: 400_000, given: 400_000, status: 'completed', lastGift: '2024-02-15', projects: ['p3','p5'] },
  { id: 'd3', name: 'Open Society Foundations', type: 'Foundation', country: 'US', amount: 120_000, given: 80_000,  status: 'active',   lastGift: '2024-03-10', projects: ['p5'] },
  { id: 'd4', name: 'DFID / FCDO',             type: 'Government', country: 'UK',  amount: 180_000, given: 140_000, status: 'active',   lastGift: '2024-01-20', projects: ['p2','p6'] },
  { id: 'd5', name: 'MasterCard Foundation',   type: 'Foundation', country: 'US',  amount: 95_000,  given: 50_000,  status: 'active',   lastGift: '2024-03-05', projects: ['p2'] },
  { id: 'd6', name: 'GIZ',                     type: 'Government', country: 'DE',  amount: 75_000,  given: 75_000,  status: 'completed', lastGift: '2024-01-10', projects: ['p1'] },
  { id: 'd7', name: 'Individual – A. Boateng', type: 'Individual', country: 'GH',  amount: 15_000,  given: 15_000,  status: 'active',   lastGift: '2024-03-18', projects: ['p4'] },
  { id: 'd8', name: 'Comic Relief',            type: 'Foundation', country: 'UK',  amount: 60_000,  given: 30_000,  status: 'active',   lastGift: '2024-02-28', projects: ['p3'] },
]

export const REPORTS = [
  { id: 'r1', title: 'Q1 2024 Impact Report',               project: 'Clean Water Initiative',    status: 'published', date: '2024-04-05', author: 'Amara Osei',     format: 'PDF' },
  { id: 'r2', title: 'Girls\' Education Mid-Year Review',   project: 'Girls\' Education Access',  status: 'draft',     date: '2024-06-15', author: 'Amara Osei',     format: 'PDF' },
  { id: 'r3', title: 'CHW Training Completion Report',      project: 'Community Health Workers',  status: 'review',    date: '2024-05-30', author: 'Dr. Kofi Ntim',  format: 'PDF' },
  { id: 'r4', title: 'Donor Quarterly Summary – Q1',        project: 'All Projects',              status: 'published', date: '2024-04-10', author: 'Adwoa Poku',     format: 'XLSX' },
  { id: 'r5', title: 'USAID Disbursement Report',           project: 'Legal Aid Clinic',          status: 'submitted', date: '2024-03-31', author: 'Adwoa Poku',     format: 'PDF' },
  { id: 'r6', title: 'Field Assessment – Tamale',           project: 'Maternal Health Outreach',  status: 'published', date: '2024-03-20', author: 'Dr. Ama Owusu',  format: 'PDF' },
]

export const FIELD_SUBMISSIONS = [
  { id: 'fs1', worker: 'Kwame Asante',   region: 'Volta',      type: 'Household Survey',    date: '2024-03-14', status: 'validated', records: 42 },
  { id: 'fs2', worker: 'Abena Mensah',   region: 'Northern',   type: 'School Enrollment',   date: '2024-03-13', status: 'validated', records: 15 },
  { id: 'fs3', worker: 'Femi Ojo',       region: 'Volta',      type: 'Water Point Audit',   date: '2024-03-13', status: 'pending',   records: 8 },
  { id: 'fs4', worker: 'Seun Adeyemi',   region: 'Northern',   type: 'Attendance Sheet',    date: '2024-03-12', status: 'validated', records: 61 },
  { id: 'fs5', worker: 'Naomi Asare',    region: 'Ashanti',    type: 'Health Screening',    date: '2024-03-12', status: 'flagged',   records: 30 },
  { id: 'fs6', worker: 'Grace Boateng',  region: 'Northern',   type: 'Community Meeting',   date: '2024-03-11', status: 'validated', records: 1 },
  { id: 'fs7', worker: 'Emmanuel Darko', region: 'Ashanti',    type: 'CHW Assessment',      date: '2024-03-11', status: 'pending',   records: 12 },
  { id: 'fs8', worker: 'Kojo Mensah',    region: 'Accra',      type: 'Legal Case Intake',   date: '2024-03-10', status: 'validated', records: 5 },
]

export const ACTIVITY_FEED = [
  { id: 'a1',  type: 'submission', actor: 'Kwame Asante',   message: 'submitted 42 household survey records',    time: '2h ago',  projectId: 'p1' },
  { id: 'a2',  type: 'report',     actor: 'Amara Osei',     message: 'published Q1 2024 Impact Report',           time: '5h ago',  projectId: 'p1' },
  { id: 'a3',  type: 'donor',      actor: 'System',         message: 'Rockefeller Foundation disbursed $30,000',  time: '1d ago',  projectId: null },
  { id: 'a4',  type: 'milestone',  actor: 'Dr. Kofi Ntim',  message: 'CHW cohort 2 training completed (30/30)',   time: '1d ago',  projectId: 'p3' },
  { id: 'a5',  type: 'flag',       actor: 'System',         message: 'Flagged: inconsistent records in fs5',      time: '2d ago',  projectId: 'p3' },
  { id: 'a6',  type: 'project',    actor: 'Yaw Darko',      message: 'Project "Smallholder Farmer" created',      time: '3d ago',  projectId: 'p4' },
  { id: 'a7',  type: 'enrollment', actor: 'Adwoa Poku',     message: '5 new beneficiaries enrolled in Legal Aid', time: '3d ago',  projectId: 'p5' },
]

export const MONTHLY_BENEFICIARIES = [
  { month: 'Oct', count: 9_100 },
  { month: 'Nov', count: 10_200 },
  { month: 'Dec', count: 11_400 },
  { month: 'Jan', count: 12_300 },
  { month: 'Feb', count: 13_600 },
  { month: 'Mar', count: 14_832 },
]

export const SPENDING_BY_SECTOR = [
  { sector: 'WASH',       amount: 74_500,  color: '#4CAF78' },
  { sector: 'Education',  amount: 52_300,  color: '#2E7D52' },
  { sector: 'Health',     amount: 93_100,  color: '#D4AF5C' },
  { sector: 'Livelihoods',amount: 5_200,   color: '#7DD4A0' },
  { sector: 'Protection', amount: 41_200,  color: '#133828' },
]

export const TEAM_MEMBERS = [
  { id: 't1', name: 'Amara Osei',      role: 'Field Coordinator',   region: 'HQ / Accra', projects: 3, status: 'active' },
  { id: 't2', name: 'Kwame Asante',    role: 'Field Officer',        region: 'Volta',      projects: 1, status: 'active' },
  { id: 't3', name: 'Dr. Kofi Ntim',   role: 'Health Specialist',    region: 'Ashanti',    projects: 1, status: 'active' },
  { id: 't4', name: 'Abena Mensah',    role: 'M&E Officer',          region: 'Northern',   projects: 2, status: 'active' },
  { id: 't5', name: 'Adwoa Poku',      role: 'Legal Officer',        region: 'Accra',      projects: 1, status: 'active' },
  { id: 't6', name: 'Yaw Darko',       role: 'Agri Specialist',      region: 'Brong-Ahafo',projects: 1, status: 'active' },
  { id: 't7', name: 'Dr. Ama Owusu',   role: 'Medical Officer',      region: 'Northern',   projects: 1, status: 'away'   },
  { id: 't8', name: 'Grace Boateng',   role: 'Education Officer',    region: 'Northern',   projects: 1, status: 'active' },
  { id: 't9', name: 'Femi Ojo',        role: 'Field Officer',        region: 'Volta',      projects: 1, status: 'active' },
  { id: 't10',name: 'Seun Adeyemi',    role: 'Field Officer',        region: 'Northern',   projects: 1, status: 'active' },
]
